### ISSUE TITLE
URL does not link to DuckDuckGo

### ISSUE THREAD

**Issue by rustzz** [sundowndev/dorkgen#20]
https://github.com/sundowndev/dorkgen/blob/8d0b63cafeac9e1cf0bd35f1ad3c0a24721eb823/duckduckgo/duckduckgo.go#L9

**Comment by sundowndev** [comment]
Thanks for pointing this out, issue has been fixed in [v1.3.1](https://github.com/sundowndev/dorkgen/releases/tag/v1.3.1).
